Roadblock
   layoutManager object is being considered null for some reason, not sure what chenged to cause this error.

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
        at com.example.jordan.beautifulbulldog.BulldogListFragment.onCreateView(BulldogListFragment.java:47)